a stupid band aid to temporarily work around a warning that comes from fmtlib trunk
/builds/cado-nfs/cado-nfs/utils/badideals.cpp:164:27:   required from here
/builds/cado-nfs/cado-nfs/utils/embedded/fmt/core.h:1735:15: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
 1735 |   const auto& arg = arg_mapper<Context>().map(FMT_FORWARD(val));
      |               ^~~
/builds/cado-nfs/cado-nfs/utils/embedded/fmt/core.h:1735:46: note: the temporary was destroyed at the end of the full expression 'fmt::v9::detail::arg_mapper<fmt::v9::basic_format_context<fmt::v9::appender, char> >().fmt::v9::detail::arg_mapper<fmt::v9::basic_format_context<fmt::v9::appender, char> >::map<cxx_mpz&>((* & val))'
 1735 |   const auto& arg = arg_mapper<Context>().map(FMT_FORWARD(val));
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~

This is the same as https://github.com/fmtlib/fmt/issues/3415